### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by selamar** [lorint/brick#4] opened 2023-04-18 14:58 UTC
/usr/local/bundle/gems/brick-1.0.131/lib/brick/frameworks/rails/engine.rb:98: warning: found `= literal' in conditional, should be ==

**Comment by lorint** [comment] 2023-04-18 22:12
> warning: found `= literal' in conditional

Not a bug -- but also not elegant that it pops that warning!

Will update to use `binding#local_variable_set` in order to suppress this warning -- expect a release within 24 hours.

BTW -- thank you for testing Brick with *.webp* images!

**Comment by lorint** [comment] 2023-04-19 06:03
Fixed in [v1.0.132](https://github.com/lorint/brick/releases/tag/v1.0.132).

Thanks much for reaching out!

**Closed as completed** 2023-04-19 06:04 UTC

**Comment by selamar** [comment] 2023-04-19 08:53
Alas, you make me waaay smarter than I am, I wasn't testing anything and I
have no .webp images that I know of. The notice just popped out during the
rails server bootstrap, I was looking because I'm trying to learn Rails.
Anyway, great job!! Glad to be useful.

Sergio

Il giorno mer 19 apr 2023 alle ore 00:12 lorint ***@***.***>
ha scritto:

**Comment by lorint** [comment] 2023-04-19 11:04
> The notice just popped out during the rails server bootstrap

Well then I'm thankful that you are keenly observant!
Depending on what Ruby version you've got, some of those warnings do or don't appear, so this could be why I hadn't seen this yet.

The Rails community is a wonderful place and I hope you have fun with this great ecosystem!

**Comment by selamar** [comment] 2023-04-19 11:07
Thanks, you too!

Il giorno mer 19 apr 2023 alle ore 13:05 lorint ***@***.***>
ha scritto:
